### PR TITLE
Clarify cleanup steps

### PR DESCRIPTION
**Pull request by shntnu**
- Removed metadata tracking because we no longer do that
- Added a section for DVC

I used https://github.com/broadinstitute/2021_09_01_VarChAMP-data as a reference when making these updates.

### CODE REVIEW

**Review by bethac07 — APPROVED** [review]

**Comment by ErinWeisbart** [comment]
I have a philosophical question - is this template intended just for our use or are we trying to encourage broader adoption? If broader, then I would leave in metadata tracking, updating language to clarify that all users should track metadata, we have a system (w/link), and if you don't have a system, use this template provided.

**Comment by shntnu** [comment]
Great point – +1 to encourage broader adoption

How is this text:

> We recommend all users, both internal and external, to diligently track project metadata. For those without a system, a template is provided below.

**Comment by shntnu** [comment]
@ErinWeisbart all set

**Comment by ErinWeisbart** [comment]
Except for the metadata log is in the Setup section and your first instructions are to delete Setup. So I suggest moving it to its own section, or clarifying that somehow. Otherwise LGTM.

**Comment by shntnu** [comment]
> Except for the metadata log is in the Setup section and your first instructions are to delete Setup. So I suggest moving it to its own section, or clarifying that somehow. Otherwise LGTM.

Ah good catch. All set now. Merging 

Thank you @bethac07 @ErinWeisbart!

**Pull request merged**
